sudo: required

services:
  - docker

script:
  - make release

after_success:
  - docker images
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push nikos/alpine-python3-flask;
    fi
